---
# tasks file for ansible-role-dc-convert

- name: Get a list of all DeploymentConfigs from any namespace
  kubernetes.core.k8s_info:
    api_key: '{{ lookup("env", "K8S_AUTH_API_KEY") | default(k8s_api_key, true) }}'
    host: '{{ lookup("env", "K8S_AUTH_HOST") | default(k8s_api_host, true) }}'
    api_version: "apps.openshift.io/v1"
    kind: DeploymentConfig
    validate_certs: false
  register: dc_list

- name: Convert All DeploymentConfigs
  include_tasks: convert.yml
  with_items: "{{ dc_list.resources }}"
